/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrew
 */
public class AndrewChat extends javax.swing.JFrame {

    /**
     * Creates new form AndrewChat
     */
    public AndrewChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        ConnectDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        IPAddressTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PortTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        NickNameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PassPasswordField = new javax.swing.JPasswordField();
        ConnectButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ClientsDialog = new javax.swing.JDialog();
        NumOfClientsTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputTextPane = new javax.swing.JTextPane();
        SendButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        InputTextArea = new javax.swing.JTextArea();
        StatusLabel = new javax.swing.JLabel();
        DiscClButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        StatusToggleButton = new javax.swing.JToggleButton();
        ClearMes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ServerStarButton = new javax.swing.JButton();
        ServerStopButton = new javax.swing.JButton();
        InfoClButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ServerOutputTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        ServerPortTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        DisconnectMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        PropetiesMenu = new javax.swing.JMenu();
        ProtetiesMenuItem = new javax.swing.JMenuItem();
        AboutMenuItem = new javax.swing.JMenuItem();

        jScrollPane3.setViewportView(jTextPane3);

        jLabel1.setText("jLabel1");

        ConnectDialog.setTitle("Propeties");
        ConnectDialog.setMinimumSize(new java.awt.Dimension(350, 400));
        ConnectDialog.setModal(true);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Connection Propeties"));

        jLabel6.setText("IP address");

        IPAddressTextField.setText("127.0.0.1");
        IPAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPAddressTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Port");

        PortTextField.setText("9001");
        PortTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IPAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PortTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(IPAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(PortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pr"));

        jLabel8.setText("Nickname");

        NickNameTextField.setText("Anonimus");
        NickNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NickNameTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Password");

        PassPasswordField.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NickNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(NickNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(PassPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConnectButton.setText("Connect");
        ConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConnectDialogLayout = new javax.swing.GroupLayout(ConnectDialog.getContentPane());
        ConnectDialog.getContentPane().setLayout(ConnectDialogLayout);
        ConnectDialogLayout.setHorizontalGroup(
            ConnectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConnectDialogLayout.createSequentialGroup()
                .addGroup(ConnectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConnectDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ConnectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ConnectDialogLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ConnectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConnectDialogLayout.setVerticalGroup(
            ConnectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConnectDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConnectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ConnectButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        ConnectDialog.getAccessibleContext().setAccessibleParent(this);

        ClientsDialog.setTitle("Clients");
        ClientsDialog.setMinimumSize(new java.awt.Dimension(200, 200));

        NumOfClientsTextField.setText("0");
        NumOfClientsTextField.setEnabled(false);

        jLabel2.setText("Number of Clients");

        javax.swing.GroupLayout ClientsDialogLayout = new javax.swing.GroupLayout(ClientsDialog.getContentPane());
        ClientsDialog.getContentPane().setLayout(ClientsDialogLayout);
        ClientsDialogLayout.setHorizontalGroup(
            ClientsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NumOfClientsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        ClientsDialogLayout.setVerticalGroup(
            ClientsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientsDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumOfClientsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Andrews Chat");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Client"));

        OutputTextPane.setToolTipText("");
        OutputTextPane.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        OutputTextPane.setEnabled(false);
        jScrollPane1.setViewportView(OutputTextPane);

        SendButton.setText("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        InputTextArea.setColumns(20);
        InputTextArea.setLineWrap(true);
        InputTextArea.setRows(5);
        jScrollPane5.setViewportView(InputTextArea);

        StatusLabel.setText("Offline");

        DiscClButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat/Shut-Down-icon.png"))); // NOI18N
        DiscClButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DiscClButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscClButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Clients");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        StatusToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat/offline.png"))); // NOI18N
        StatusToggleButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/chat/offline.png"))); // NOI18N
        StatusToggleButton.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/chat/online.png"))); // NOI18N
        StatusToggleButton.setEnabled(false);
        StatusToggleButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/chat/online.png"))); // NOI18N

        ClearMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat/gnome_edit_clear.png"))); // NOI18N
        ClearMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(SendButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClearMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DiscClButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(StatusLabel)
                    .addComponent(StatusToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(DiscClButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClearMes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SendButton))
        );

        DiscClButton.getAccessibleContext().setAccessibleDescription("Disconnect");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Server"));

        ServerStarButton.setText("Start");
        ServerStarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerStarButtonActionPerformed(evt);
            }
        });

        ServerStopButton.setText("Stop");
        ServerStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerStopButtonActionPerformed(evt);
            }
        });

        InfoClButton.setText("Clients");
        InfoClButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoClButtonActionPerformed(evt);
            }
        });

        ServerOutputTextArea.setColumns(20);
        ServerOutputTextArea.setLineWrap(true);
        ServerOutputTextArea.setRows(5);
        ServerOutputTextArea.setEnabled(false);
        jScrollPane2.setViewportView(ServerOutputTextArea);

        jLabel3.setText("Port");

        ServerPortTextField.setText("9001");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat/gnome_edit_clear.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ServerPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ServerStopButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ServerStarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoClButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {InfoClButton, ServerStarButton, ServerStopButton});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ServerStarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServerStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoClButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ServerPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {InfoClButton, ServerStarButton, ServerStopButton});

        jMenu1.setText("File");

        jMenuItem2.setText("Connect");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        DisconnectMenuItem.setText("Disconnect");
        DisconnectMenuItem.setEnabled(false);
        DisconnectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisconnectMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(DisconnectMenuItem);

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        PropetiesMenu.setText("Propeties");

        ProtetiesMenuItem.setText("Propeties");
        ProtetiesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProtetiesMenuItemActionPerformed(evt);
            }
        });
        PropetiesMenu.add(ProtetiesMenuItem);

        AboutMenuItem.setText("About");
        PropetiesMenu.add(AboutMenuItem);

        jMenuBar1.add(PropetiesMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProtetiesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProtetiesMenuItemActionPerformed
        // TODO add your handling code here:
        ConnectDialog.setLocationRelativeTo(null);
        ConnectDialog.setVisible(true);
    }//GEN-LAST:event_ProtetiesMenuItemActionPerformed

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        // TODO add your handling code here:
        if(ChCl != null) {
            if(!InputTextArea.getText().equals(""))
                ChCl.sendMess(InputTextArea.getText());   
        }
        else {
            JOptionPane.showMessageDialog(this,
                                    "Doesn't Connected",
                                    "No connection",
                                    JOptionPane.INFORMATION_MESSAGE);
        }
        InputTextArea.setText("");
        
    }//GEN-LAST:event_SendButtonActionPerformed

    private void ServerStarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerStarButtonActionPerformed
        // TODO add your handling code here:
        
        ChServer = new ChatServer(ServerOutputTextArea);
        ChatServer.setPort(ServerPortTextField.getText());
        
        try {
            ChServer.start();
        } catch(Exception e) {
            ServerOutputTextArea.append("Can't start server/n");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_ServerStarButtonActionPerformed

    private void InfoClButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoClButtonActionPerformed
        // TODO add your handling code here:
        NumOfClientsTextField.setText(Integer.toString(ChServer.getNumOfClients()));
        ClientsDialog.setLocationRelativeTo(null);
        ClientsDialog.setVisible(true);
    }//GEN-LAST:event_InfoClButtonActionPerformed

    private void ServerStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerStopButtonActionPerformed
        // TODO add your handling code here:
        if(ChServer != null) {
            ChServer.Serv_Stop();
            ServerOutputTextArea.append("Server has stopped.\n");
        }
        DisconnectMenuItem.setEnabled(false);
    }//GEN-LAST:event_ServerStopButtonActionPerformed

    private void PortTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortTextFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        ConnectDialog.setVisible(false);
        ConnectDialog.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectButtonActionPerformed
        // TODO add your handling code here:
        OutputTextPane.setText("");
        ChCl = new ChatClient(InputTextArea, OutputTextPane);
        ChCl.setClientInfo(NickNameTextField.getText(), PassPasswordField.getPassword().toString(), IPAddressTextField.getText(), PortTextField.getText());
        ConnectDialog.dispose();
        
        try {
            ChCl.start();
            DisconnectMenuItem.setEnabled(true);
            StatusLabel.setText("Online");
            StatusToggleButton.setSelected(true);
        }
        catch(Exception e) {
            StatusLabel.setText("Offline");
            DisconnectMenuItem.setEnabled(false);
            StatusToggleButton.setSelected(false);
            e.printStackTrace();
        }
    }//GEN-LAST:event_ConnectButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //setVisible(false);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void NickNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NickNameTextFieldActionPerformed
        // TODO add your handling code here:
        NickNameTextField.getText();
        PortTextField.getText();
        IPAddressTextField.getText();
    }//GEN-LAST:event_NickNameTextFieldActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ConnectDialog.setLocationRelativeTo(null);
        ConnectDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void IPAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPAddressTextFieldActionPerformed

    private void DisconnectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnectMenuItemActionPerformed
        // TODO add your handling code here:
        if(ChCl != null){
            ChCl.dis();
            StatusLabel.setText("Offline");
            DisconnectMenuItem.setEnabled(false);
            StatusToggleButton.setSelected(false);
        }  
    }//GEN-LAST:event_DisconnectMenuItemActionPerformed

    private void DiscClButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscClButtonActionPerformed
        // TODO add your handling code here:
        if(ChCl != null){
            ChCl.dis();
            StatusLabel.setText("Offline");
            DisconnectMenuItem.setEnabled(false);
            StatusToggleButton.setSelected(false);
        }
    }//GEN-LAST:event_DiscClButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClearMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearMesActionPerformed
        // TODO add your handling code here:
        OutputTextPane.setText("");
    }//GEN-LAST:event_ClearMesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ServerOutputTextArea.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndrewChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndrewChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndrewChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndrewChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AndrewChat().setVisible(true);
            }
        });
    }
    private ChatClient ChCl;
    private ChatServer ChServer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuItem;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton ClearMes;
    private javax.swing.JDialog ClientsDialog;
    private javax.swing.JButton ConnectButton;
    private javax.swing.JDialog ConnectDialog;
    private javax.swing.JButton DiscClButton;
    private javax.swing.JMenuItem DisconnectMenuItem;
    private javax.swing.JTextField IPAddressTextField;
    private javax.swing.JButton InfoClButton;
    private javax.swing.JTextArea InputTextArea;
    private javax.swing.JTextField NickNameTextField;
    private javax.swing.JTextField NumOfClientsTextField;
    private javax.swing.JTextPane OutputTextPane;
    private javax.swing.JPasswordField PassPasswordField;
    private javax.swing.JTextField PortTextField;
    private javax.swing.JMenu PropetiesMenu;
    private javax.swing.JMenuItem ProtetiesMenuItem;
    private javax.swing.JButton SendButton;
    private javax.swing.JTextArea ServerOutputTextArea;
    private javax.swing.JTextField ServerPortTextField;
    private javax.swing.JButton ServerStarButton;
    private javax.swing.JButton ServerStopButton;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JToggleButton StatusToggleButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
